# Application Configuration
base.url=https://opensource-demo.orangehrmlive.com/web/index.php/auth/login
browser=chrome
implicit.wait=10
screenshot.path=./screenshots/

# Credentials
username=Admin
password=admin123
